deployment:
  ingress:
  
    annotations:
      nginx.ingress.kubernetes.io/enable-cors: "true"
      
      # Forward auth configuration using your gateway service
      nginx.ingress.kubernetes.io/auth-url: "http://mindsdb-gateway.gitlab-dev.svc.cluster.local:80/cloud/llm/api-key/"
    hosts:
      - host: minds-gitlab.dev.mdb.ai
        enableMultiPath: true
        paths:
          - path: /
            serviceName: minds
            servicePort: 80
      
      - host: gitlab.dev.mdb.ai
        enableMultiPath: true
        paths:
          - path: /api/v1/chat
            serviceName: minds
            servicePort: 80
          - path: /api/v1/minds
            serviceName: minds
            servicePort: 80
          - path: /api/v1/datasources
            serviceName: minds
            servicePort: 80
          - path: /api/v1/tree
            serviceName: minds
            servicePort: 80
      - host: demo3.mdb.ai
        enableMultiPath: true
        paths:
          - path: /api/v1/chat
            serviceName: minds
            servicePort: 80
          - path: /api/v1/minds
            serviceName: minds
            servicePort: 80
          - path: /api/v1/datasources
            serviceName: minds
            servicePort: 80
          - path: /api/v1/tree
            serviceName: minds
            servicePort: 80

  extraEnvs:

    # Langfuse
    - name: LANGFUSE_ENVIRONMENT
      value: "gitlab-dev"

    # Data Catalog
    - name: DATA_CATALOG_JOB_DEPLOYMENT_NAME
      value: "gitlab-dev--data-catalog-loader"
