deployment:
  ingress:
    hosts:
      - host: minds-curtiss-wright.dev.mdb.ai
        enableMultiPath: true
        paths:
          - path: /
            serviceName: minds
            servicePort: 80
