deployment:
  ingress:
    hosts:
      - host: minds.staging.mdb.ai
        enableMultiPath: true
        paths:
          - path: /
            serviceName: minds
            servicePort: 80

  extraEnvs:

    # Langfuse
    - name: LANGFUSE_ENVIRONMENT
      value: "staging"
