deployment:
  ingress:
    hosts:
      - host: minds-alpha.dev.mdb.ai
        enableMultiPath: true
        paths:
          - path: /
            serviceName: minds
            servicePort: 80
      
      - host: alpha.dev.mdb.ai
        enableMultiPath: true
        paths:
          - path: /api/v1/chat
            serviceName: minds
            servicePort: 80
          - path: /api/v1/minds
            serviceName: minds
            servicePort: 80
          - path: /api/v1/datasources
            serviceName: minds
            servicePort: 80
          - path: /api/v1/tree
            serviceName: minds
            servicePort: 80

  extraEnvs:

    # Langfuse
    - name: LANGFUSE_ENVIRONMENT
      value: "alpha-dev"
