deployment:
  serviceAccount:
    enabled: true
    annotations:
      # Gives permission to use the mind-castle kms key
      eks.amazonaws.com/role-arn: arn:aws:iam::168681354662:role/minds-20260204203650912200000002

  ingress:
    name: minds
    annotations:
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-origin: "https://console.dev.mindshub.ai, https://dev.mdb.ai, https://hub.dev.mindsdb.com"
      nginx.ingress.kubernetes.io/auth-url: "http://auth.dev.svc.cluster.local:80/v1/authenticate/"
    hosts:
      - host: api.dev.mindshub.ai
        enableMultiPath: true
        paths:
          - path: /v1
            serviceName: minds
            servicePort: 80
  
  extraEnvs:

    # ====================================
    # GENERAL SETTINGS
    # ====================================

    - name: ENV
      value: "dev"

    # ====================================
    # LOGGING SETTINGS
    # ====================================

    - name: LOG_LEVEL
      value: "WARNING"

    # ====================================
    # LANGFUSE SETTINGS
    # ====================================

    - name: LANGFUSE_TRACING_ENVIRONMENT
      value: "dev"

    # ====================================
    # MIND CASTLE SETTINGS
    # ====================================

    - name: MIND_CASTLE_AWS_KMS_KEY_ARN
      value: "arn:aws:kms:us-east-1:168681354662:key/679a2faa-925c-4da3-bc27-d4adbdcbcb13"

    # ====================================
    # STATSIG SETTINGS
    # ====================================

    - name: STATSIG__ENVIRONMENT
      value: "development"
          