deployment:
  ingress:
  
    annotations:
      # Forward auth configuration using your gateway service
      nginx.ingress.kubernetes.io/auth-url: "http://mindsdb-gateway.prod.svc.cluster.local:80/cloud/llm/api-key/"
    hosts:
      - host: minds.mdb.ai
        enableMultiPath: true
        paths:
          - path: /
            serviceName: minds
            servicePort: 80
      
      - host: mdb.ai
        enableMultiPath: true
        paths:
          - path: /api/v1/chat
            serviceName: minds
            servicePort: 80
          - path: /api/v1/minds
            serviceName: minds
            servicePort: 80
          - path: /api/v1/datasources
            serviceName: minds
            servicePort: 80
          - path: /api/v1/tree
            serviceName: minds
            servicePort: 80

  extraEnvs:

    # Langfuse
    - name: LANGFUSE_ENVIRONMENT
      value: "prod"

    - name: LANGFUSE_TRACING_ENABLED
      value: "false"

    - name: LANGFUSE_PUBLIC_KEY
      value: "remove"

    - name: LANGFUSE_SECRET_KEY
      value: "remove"

    # Data Catalog
    - name: DATA_CATALOG_JOB_DEPLOYMENT_NAME
      value: "prod--data-catalog-loader"
