deployment:
  serviceAccount:
    enabled: true
    annotations:
      # Gives permission to use the mind-castle kms key
      eks.amazonaws.com/role-arn: arn:aws:iam::065786718370:role/minds-20260204214712848900000002
  
  ingress:
    annotations:
      # Forward auth configuration using your gateway service
      nginx.ingress.kubernetes.io/auth-url: "http://auth.prod.svc.cluster.local:80/api/v1/authenticate/"
    hosts:
      - host: minds.mdb.ai
        enableMultiPath: true
        paths:
          - path: /
            serviceName: minds
            servicePort: 80
      
      - host: mdb.ai
        enableMultiPath: true
        paths:
          - path: /api/v1/chat
            serviceName: minds
            servicePort: 80
          - path: /api/v1/minds
            serviceName: minds
            servicePort: 80
          - path: /api/v1/datasources
            serviceName: minds
            servicePort: 80
          - path: /api/v1/tree
            serviceName: minds
            servicePort: 80
          - path: /api/v1/conversations
            serviceName: minds
            servicePort: 80
          - path: /api/v1/responses
            serviceName: minds
            servicePort: 80
          - path: /api/v1/limits
            serviceName: minds
            servicePort: 80
  extraEnvs:

    # ====================================
    # GENERAL SETTINGS
    # ====================================

    - name: ENV
      value: "prod"

    # ====================================
    # LOGGING SETTINGS
    # ====================================

    - name: LOG_LEVEL
      value: "WARNING"

    # ====================================
    # LANGFUSE SETTINGS
    # ====================================

    - name: LANGFUSE_TRACING_ENVIRONMENT
      value: "prod"

    # ====================================
    # DATA CATALOG SETTINGS
    # ====================================

    - name: DATA_CATALOG__JOB_DEPLOYMENT_NAME
      value: "prod--data-catalog-loader"

    # ====================================
    # MIND CASTLE SETTINGS
    # ====================================

    - name: MIND_CASTLE_AWS_KMS_KEY_ARN
      value: "arn:aws:kms:us-east-1:065786718370:key/1787cc0e-18e5-4c7d-af9f-6f9f01b06f17"
    
    # ====================================
    # STATSIG SETTINGS
    # ====================================

    - name: STATSIG__ENVIRONMENT
      value: "production"
          
