deployment:
  ingress:
  
    annotations:
      nginx.ingress.kubernetes.io/enable-cors: "true"
      
      # Forward auth configuration using your gateway service
      nginx.ingress.kubernetes.io/auth-url: "http://mindsdb-gateway.terabase-dev.svc.cluster.local:80/cloud/llm/api-key/"
    hosts:
      
      - host: minds-terabase.dev.mdb.ai
        enableMultiPath: true
        paths:
          - path: /
            serviceName: minds
            servicePort: 80
      
      - host: terabase.dev.mdb.ai
        enableMultiPath: true
        paths:
          - path: /api/v1/chat
            serviceName: minds
            servicePort: 80
          - path: /api/v1/minds
            serviceName: minds
            servicePort: 80
          - path: /api/v1/datasources
            serviceName: minds
            servicePort: 80
          - path: /api/v1/tree
            serviceName: minds
            servicePort: 80

  extraEnvs:

    # ====================================
    # GENERAL SETTINGS
    # ====================================

    - name: ENV
      value: "terabase-dev"

    # ====================================
    # LANGFUSE SETTINGS
    # ====================================

    - name: LANGFUSE_TRACING_ENVIRONMENT
      value: "terabase-dev"

    # ====================================
    # DATA CATALOG SETTINGS
    # ====================================

    - name: DATA_CATALOG__JOB_DEPLOYMENT_NAME
      value: "terabase-dev--data-catalog-loader"
