services:

  # Auto-restarts containers that are unhealthy
  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    <<: &autoRestartOnFailure
      deploy:
        restart_policy:
          condition: on-failure
          max_attempts: 10

  postgres:
    image: postgres:16.4
    <<: *autoRestartOnFailure
    restart: unless-stopped
    ports:
      - "35432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./scripts/init-dbs.sh:/docker-entrypoint-initdb.d/init-dbs.sh
    depends_on:
      autoheal:
        condition: service_healthy
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 4s
      retries: 5

  pg-init:
    image: postgres:16.4
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGHOST: postgres
      PGPORT: "5432"
      PGUSER: postgres
      PGPASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./scripts:/scripts:ro
    entrypoint:
      ["/bin/bash","-lc",
       "set -euo pipefail;
        bash /scripts/init-dbs.sh"
      ]
    restart: "no"

  redis:
    image: redis:8.2.1
    <<: *autoRestartOnFailure
    restart: unless-stopped
    ports:
      - '16379:6379'
    depends_on:
      autoheal:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 30

  clickhouse:
    image: clickhouse/clickhouse-server:25.7.4
    <<: *autoRestartOnFailure
    restart: unless-stopped
    ports:
      - 18123:8123
      - 19000:9000
    volumes:
      - ch_data:/var/lib/clickhouse
      - ch_logs:/var/log/clickhouse-server
    environment:
      CLICKHOUSE_DB: clickhouse
      CLICKHOUSE_USER: clickhouse
      CLICKHOUSE_PASSWORD: clickhouse
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      TZ: UTC
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --query='SELECT 1' || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 30s

  minio:
    image: minio/minio:latest
    <<: *autoRestartOnFailure
    restart: unless-stopped
    depends_on:
      autoheal:
        condition: service_healthy
    ports:
      - "19002:9000"
      - "19001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniosecret
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio-init:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
        /usr/bin/mc alias set local http://minio:9000 minio miniosecret &&
        /usr/bin/mc mb -p local/langfuse || true
      "
    restart: "no"


  langfuse-web:
    image: langfuse/langfuse:3.101.0
    <<: *autoRestartOnFailure
    restart: unless-stopped
    ports:
      - "13000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      autoheal:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
      minio-init:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: "postgresql://langfuse:langfuse@postgres/langfuse"
      NEXTAUTH_SECRET: Reosi8Qn7obpoXoiSHIK975ZzffH/1OvZaVk4a+moUA= # generate secret with at least 256 entropy using `openssl rand -base64 32`.
      SALT: plNYAdUp/lOpdYvt61d+us/elglz5WGedKTU65+coB4= # generate secret with at least 256 entropy using `openssl rand -base64 32`.
      ENCRYPTION_KEY: a77962b28ceb28f58ce4b247ff7c97685e072d99052f9de0a398f3539b767f2f # generate secret with at least 256 bits and 64 characters in hex format using `openssl rand -hex 32`.
      NEXTAUTH_URL: http://localhost:13000
      LANGFUSE_INIT_ORG_ID: mindsdb # Organization ID
      LANGFUSE_INIT_ORG_NAME: MindsDB # Organization name
      LANGFUSE_INIT_PROJECT_ID: 23152f1d-9604-4629-a69d-27790d47b7fa # Project ID (UUID)
      LANGFUSE_INIT_PROJECT_NAME: MindsDB # Project name
      LANGFUSE_INIT_PROJECT_PUBLIC_KEY: redacted # Project public key
      LANGFUSE_INIT_PROJECT_SECRET_KEY: redacted # Project secret key
      LANGFUSE_INIT_USER_EMAIL: admin@langfuse.com # User email
      LANGFUSE_INIT_USER_NAME: User # User name
      LANGFUSE_INIT_USER_PASSWORD: password # User password

      LANGFUSE_LOG_LEVEL: info

      # Clickhouse
      CLICKHOUSE_MIGRATION_URL: clickhouse://clickhouse:9000
      CLICKHOUSE_URL: http://clickhouse:8123
      CLICKHOUSE_USER: clickhouse
      CLICKHOUSE_PASSWORD: clickhouse
      CLICKHOUSE_CLUSTER_ENABLED: false

      # Redis
      REDIS_CONNECTION_STRING: redis://redis:6379

      # Minio
      LANGFUSE_S3_EVENT_UPLOAD_ENABLED: true
      LANGFUSE_S3_EVENT_UPLOAD_BUCKET: langfuse
      LANGFUSE_S3_EVENT_UPLOAD_REGION: auto
      LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT: http://minio:9000
      LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY: minio
      LANGFUSE_S3_EVENT_UPLOAD_SECRET_KEY: miniosecret
      LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE: true
      LANGFUSE_AUTO_CLICKHOUSE_MIGRATION_DISABLED: false

      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: miniosecret
      AWS_REGION: us-east-1
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://$(hostname):3000/api/public/health"]
      interval: 30s
      timeout: 29s
      retries: 10

  langfuse-worker:
    image: langfuse/langfuse-worker:3.101.0
    <<: *autoRestartOnFailure
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      autoheal:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
      minio-init:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: "postgresql://langfuse:langfuse@postgres/langfuse"
      NEXTAUTH_SECRET: Reosi8Qn7obpoXoiSHIK975ZzffH/1OvZaVk4a+moUA= # generate secret with at least 256 entropy using `openssl rand -base64 32`.
      SALT: plNYAdUp/lOpdYvt61d+us/elglz5WGedKTU65+coB4= # generate secret with at least 256 entropy using `openssl rand -base64 32`.
      ENCRYPTION_KEY: a77962b28ceb28f58ce4b247ff7c97685e072d99052f9de0a398f3539b767f2f # generate secret with at least 256 bits and 64 characters in hex format using `openssl rand -hex 32`.
      NEXTAUTH_URL: http://localhost:13000
      LANGFUSE_INIT_ORG_ID: mindsdb # Organization ID
      LANGFUSE_INIT_ORG_NAME: MindsDB # Organization name
      LANGFUSE_INIT_PROJECT_ID: 23152f1d-9604-4629-a69d-27790d47b7fa # Project ID (UUID)
      LANGFUSE_INIT_PROJECT_NAME: MindsDB # Project name
      LANGFUSE_INIT_PROJECT_PUBLIC_KEY: redacted # Project public key
      LANGFUSE_INIT_PROJECT_SECRET_KEY: redacted # Project secret key
      LANGFUSE_INIT_USER_EMAIL: admin@langfuse.com # User email
      LANGFUSE_INIT_USER_NAME: User # User name
      LANGFUSE_INIT_USER_PASSWORD: password # User password

      LANGFUSE_LOG_LEVEL: info

      # Clickhouse
      CLICKHOUSE_MIGRATION_URL: clickhouse://clickhouse:9000
      CLICKHOUSE_URL: http://clickhouse:8123
      CLICKHOUSE_USER: clickhouse
      CLICKHOUSE_PASSWORD: clickhouse
      CLICKHOUSE_CLUSTER_ENABLED: false

      # Redis
      REDIS_CONNECTION_STRING: redis://redis:6379

      # Minio
      LANGFUSE_S3_EVENT_UPLOAD_ENABLED: true
      LANGFUSE_S3_EVENT_UPLOAD_BUCKET: langfuse
      LANGFUSE_S3_EVENT_UPLOAD_REGION: auto
      LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT: http://minio:9000
      LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY: minio
      LANGFUSE_S3_EVENT_UPLOAD_SECRET_KEY: miniosecret
      LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE: true
      LANGFUSE_AUTO_CLICKHOUSE_MIGRATION_DISABLED: false

      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: miniosecret
      AWS_REGION: us-east-1
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://$(hostname):3030/api/health"]
      interval: 30s
      timeout: 29s
      retries: 10

  prefect-server:
    image: prefecthq/prefect:3.4.19-python3.13
    <<: *autoRestartOnFailure
    restart: unless-stopped
    command: prefect server start --no-services
    depends_on:
      autoheal:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      pg-init:
        condition: service_completed_successfully
    environment:
      PREFECT_API_DATABASE_CONNECTION_URL: postgresql+asyncpg://prefect:prefect@postgres/prefect
      PREFECT_SERVER_API_HOST: 0.0.0.0
      PREFECT_UI_API_URL: http://localhost:4200/api
      PREFECT_MESSAGING_BROKER: prefect_redis.messaging
      PREFECT_MESSAGING_CACHE: prefect_redis.messaging
      PREFECT_REDIS_MESSAGING_HOST: redis
      PREFECT_REDIS_MESSAGING_PORT: 6379
      PREFECT_REDIS_MESSAGING_DB: 0
    ports:
      - "4200:4200"

  prefect-services:
    image: prefecthq/prefect:3.4.19-python3.13
    <<: *autoRestartOnFailure
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      pg-init:
        condition: service_completed_successfully
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api   # points to server from inside Docker
      PREFECT_API_DATABASE_CONNECTION_URL: postgresql+asyncpg://prefect:prefect@postgres/prefect
      PREFECT_MESSAGING_BROKER: prefect_redis.messaging
      PREFECT_MESSAGING_CACHE: prefect_redis.messaging
      PREFECT_REDIS_MESSAGING_HOST: redis
      PREFECT_REDIS_MESSAGING_PORT: 6379
      PREFECT_REDIS_MESSAGING_DB: 0
    command: prefect server services start

  prefect-worker:
    image: prefecthq/prefect:3.4.19-python3.13
    <<: *autoRestartOnFailure
    depends_on:
      prefect-server:
        condition: service_started
      prefect-services:
        condition: service_started
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api
    command: prefect worker start --pool standard-worker-pool --type docker --install-policy always


  mindsdb:
    build:
      context: ../mindsdb
      dockerfile: docker/mindsdb.Dockerfile
    <<: *autoRestartOnFailure
    restart: unless-stopped
    ports:
      - "47334:47334"
      - "47335:47335"
    volumes:
      - mindsdb_data:/opt/mindsdb
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:47334/api/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    depends_on:
      autoheal:
        condition: service_healthy

  migrate:
    build:
      context: .
    <<: *autoRestartOnFailure
    platform: linux/amd64
    command: ["python", "-m", "alembic", "upgrade", "head"]
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE__URI: postgresql://minds:minds@postgres/minds
    restart: "no"

  minds-flows:
    build:
      context: .
    image: minds-flows:latest
    <<: *autoRestartOnFailure
    platform: linux/amd64
    command: ["make", "prefect/docker/deploy/full"]
    restart: "no"
    depends_on:
      migrate:
        condition: service_completed_successfully
      prefect-server:
        condition: service_started
      prefect-services:
        condition: service_started
      prefect-worker:
        condition: service_started
    volumes:
      - .:/minds
    environment:
      ENV: local
      LOG_LEVEL: DEBUG

      IMAGE_NAME: minds-flows
      IMAGE_TAG: latest

      DATABASE__URI: postgresql://minds:minds@postgres/minds

      # MindsDB configuration
      MINDSDB__URL: "http://mindsdb:47334"

      OPENAI__API_URL: "${OPENAI_API_URL}"
      OPENAI__API_KEY: "${OPENAI_API_KEY}"

      LANGFUSE_PUBLIC_KEY: "redacted"
      LANGFUSE_SECRET_KEY: "redacted"
      LANGFUSE_HOST: "http://langfuse:3000"
      LANGFUSE_ENABLED: "${LANGFUSE_ENABLED}"

      # Auth
      AUTH__DISABLE: "true" # Disable auth for local development

      # Data Catalog
      DATA_CATALOG__EXECUTION_MODE: asynchronous

      # Prefect
      PREFECT_API_URL: http://host.docker.internal:4200/api
    env_file:
      - .env

  minds:
    build:
      context: .
    <<: *autoRestartOnFailure
    platform: linux/amd64
    entrypoint: sh -c "python -m watchfiles --filter python 'python -m uvicorn minds.server:app --workers 1 --host 0.0.0.0 --port 9010' ."
    restart: unless-stopped
    depends_on:
      migrate:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      langfuse-web:
        condition: service_healthy
      langfuse-worker:
        condition: service_healthy
      mindsdb:
        condition: service_healthy
      prefect-server:
        condition: service_started
      prefect-services:
        condition: service_started
      prefect-worker:
        condition: service_started
    ports:
      - "9010:9010"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9010/api/v1/health/" ]
      interval: 10s
      timeout: 9s
      retries: 5
    environment:
      ENV: local
      LOG_LEVEL: DEBUG

      DATABASE__URI: postgresql://minds:minds@postgres/minds

      # MindsDB configuration
      MINDSDB__URL: "http://mindsdb:47334"
      MINDSDB__LOGIN: "${MINDSDB_LOGIN}"
      MINDSDB__PASSWORD: "${MINDSDB_PASSWORD}"

      OPENAI__API_URL: "${OPENAI_API_URL}"
      OPENAI__API_KEY: "${OPENAI_API_KEY}"

      # Auth
      AUTH__DISABLE: "true" # Disable auth for local development

      # Data Catalog
      DATA_CATALOG__EXECUTION_MODE: asynchronous

      # Prefect
      PREFECT_API_URL: http://prefect-server:4200/api

      LANGFUSE_PUBLIC_KEY: "redacted"
      LANGFUSE_SECRET_KEY: "redacted"
      LANGFUSE_HOST: "http://langfuse:3000"
      LANGFUSE_ENABLED: "${LANGFUSE_ENABLED}"
    env_file:
      - .env

volumes:
  postgres:
  ch_data:
  ch_logs:
  minio_data:
  mindsdb_data:

networks:
  default:
