"""Add minds table with UUID primary key

Revision ID: 001_add_minds_table_with_uuid
Revises: 
Create Date: 2025-01-11 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001_add_minds_table_with_uuid'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable the uuid-ossp extension for gen_random_uuid()
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    
    # Create minds table
    op.create_table(
        'minds',
        sa.Column(
            'id',
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text('gen_random_uuid()'),
            nullable=False,
            comment='UUID primary key generated by PostgreSQL'
        ),
        sa.Column(
            'name',
            sa.String(),
            nullable=False,
            comment='Name of the mind'
        ),
        sa.Column(
            'created_on',
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=True,
            comment='The date and time the record was created. Field is optional and not needed when instantiating a new record. It will be automatically set when the record is created in the database.'
        ),
        sa.Column(
            'modified_on',
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=True,
            comment='The date and time the record was updated. Field is optional and not needed when instantiating a new record. It will be automatically set when the record is created in the database.'
        ),
        comment='Minds table with UUID primary key and automatic timestamps'
    )
    
    # Add trigger for updating modified_on timestamp
    op.execute("""
        CREATE OR REPLACE FUNCTION update_modified_on_column()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.modified_on = now();
            RETURN NEW;
        END;
        $$ language 'plpgsql';
    """)
    
    op.execute("""
        CREATE TRIGGER update_minds_modified_on 
        BEFORE UPDATE ON minds 
        FOR EACH ROW 
        EXECUTE FUNCTION update_modified_on_column();
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # Drop trigger and function
    op.execute('DROP TRIGGER IF EXISTS update_minds_modified_on ON minds')
    op.execute('DROP FUNCTION IF EXISTS update_modified_on_column()')
    
    # Drop table
    op.drop_table('minds')
    
    # Note: We don't drop the uuid-ossp extension as it might be used by other tables
