"""initial_schema_complete

Create complete initial schema with:
- minds table
- datasources table  
- mind_datasources junction table (many-to-many relationship)

Revision ID: 001_initial_schema_complete
Revises: 
Create Date: 2025-08-29 15:30:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '001_initial_schema_complete'
down_revision: str | None = None  # This is the initial migration
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the complete initial schema."""
    
    # 1. Create minds table
    op.create_table('minds',
        sa.Column(
            'id',
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text('gen_random_uuid()'),
            nullable=False,
            comment='UUID primary key generated by PostgreSQL'
        ),
        sa.Column(
            'tenant_id',
            postgresql.UUID(as_uuid=True),
            nullable=True,
            comment='Tenant ID'
        ),
        sa.Column(
            'created_at', 
            sa.DateTime(timezone=True), 
            nullable=True,
            server_default=sa.text('now()'),
            comment='The date and time the record was created'
        ),
        sa.Column(
            'modified_at', 
            sa.DateTime(timezone=True), 
            nullable=True,
            server_default=sa.text('now()'),
            comment='The date and time the record was updated'
        ),
        sa.Column(
            'deleted_at', 
            sa.DateTime(timezone=True), 
            nullable=True,
            comment='The date and time the record was deleted'
        ),
        sa.Column('name', sa.String(length=256), nullable=False, comment='Name of the mind'),
        sa.Column('provider', sa.String(length=50), nullable=False),
        sa.Column('model_name', sa.String(length=256), nullable=False),
        sa.Column('user_id', sa.String(length=256), nullable=False),
        sa.Column('parameters', sa.JSON(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name', 'user_id', 'deleted_at', name='unique_mind_name_per_user'),
        comment='Minds table with UUID primary key and automatic timestamps'
    )
    
    # Create indexes for minds table
    op.create_index('ix_minds_name', 'minds', ['name'])
    op.create_index('ix_minds_user_id', 'minds', ['user_id'])
    
    # 2. Create datasources table
    op.create_table('datasources',
        sa.Column(
            'id',
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text('gen_random_uuid()'),
            nullable=False,
            comment='UUID primary key generated by PostgreSQL'
        ),
        sa.Column(
            'tenant_id',
            postgresql.UUID(as_uuid=True),
            nullable=True,
            comment='Tenant ID'
        ),
        sa.Column(
            'created_at', 
            sa.DateTime(timezone=True), 
            nullable=True,
            server_default=sa.text('now()'),
            comment='The date and time the record was created'
        ),
        sa.Column(
            'modified_at', 
            sa.DateTime(timezone=True), 
            nullable=True,
            server_default=sa.text('now()'),
            comment='The date and time the record was updated'
        ),
        sa.Column(
            'deleted_at', 
            sa.DateTime(timezone=True), 
            nullable=True,
            comment='The date and time the record was deleted'
        ),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('engine', sa.String(length=50), nullable=False),
        sa.Column('connection_data', sa.JSON(), nullable=True),
        sa.Column('user_id', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name', 'user_id', 'deleted_at', name='unique_datasource_name_per_user'),
        comment='Datasources table for storing database connection information'
    )
    
    # 3. Create mind_datasources junction table
    op.create_table('mind_datasources',
        sa.Column(
            'id',
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text('gen_random_uuid()'),
            nullable=False,
            comment='UUID primary key generated by PostgreSQL'
        ),
        sa.Column(
            'tenant_id',
            postgresql.UUID(as_uuid=True),
            nullable=True,
            comment='Tenant ID'
        ),
        sa.Column(
            'created_at', 
            sa.DateTime(timezone=True), 
            nullable=True,
            server_default=sa.text('now()'),
            comment='The date and time the record was created'
        ),
        sa.Column(
            'modified_at', 
            sa.DateTime(timezone=True), 
            nullable=True,
            server_default=sa.text('now()'),
            comment='The date and time the record was updated'
        ),
        sa.Column(
            'deleted_at', 
            sa.DateTime(timezone=True), 
            nullable=True,
            comment='The date and time the record was deleted'
        ),
        sa.Column('mind_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('datasource_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('tables', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('purpose', sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(['mind_id'], ['minds.id']),
        sa.ForeignKeyConstraint(['datasource_id'], ['datasources.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('mind_id', 'datasource_id', 'deleted_at', name='unique_mind_datasource_pair'),
        comment='Junction table linking minds to datasources (many-to-many relationship)'
    )
    
    # Create indexes for better performance
    op.create_index('ix_mind_datasources_mind_id', 'mind_datasources', ['mind_id'])
    op.create_index('ix_mind_datasources_datasource_id', 'mind_datasources', ['datasource_id'])
    
    # 4. Create the uuid-ossp extension for UUID generation
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    
    # 5. Create function for automatically updating modified_at timestamps
    op.execute('''
        CREATE OR REPLACE FUNCTION update_modified_at_column()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.modified_at= now();
            RETURN NEW;
        END;
        $$ language 'plpgsql';
    ''')
    
    # 6. Create triggers for automatic timestamp updates
    op.execute('''
        CREATE TRIGGER update_minds_modified_at 
        BEFORE UPDATE ON minds 
        FOR EACH ROW EXECUTE FUNCTION update_modified_at_column();
    ''')
    
    op.execute('''
        CREATE TRIGGER update_datasources_modified_at
        BEFORE UPDATE ON datasources 
        FOR EACH ROW EXECUTE FUNCTION update_modified_at_column();
    ''')
    
    op.execute('''
        CREATE TRIGGER update_mind_datasources_modified_at 
        BEFORE UPDATE ON mind_datasources 
        FOR EACH ROW EXECUTE FUNCTION update_modified_at_column();
    ''')


def downgrade() -> None:
    """Drop all tables and functions."""
    
    # Drop triggers
    op.execute('DROP TRIGGER IF EXISTS update_mind_datasources_modified_at ON mind_datasources;')
    op.execute('DROP TRIGGER IF EXISTS update_datasources_modified_at ON datasources;')
    op.execute('DROP TRIGGER IF EXISTS update_minds_modified_at ON minds;')
    
    # Drop function
    op.execute('DROP FUNCTION IF EXISTS update_modified_at_column();')
    
    # Drop tables (in reverse order due to foreign keys)
    op.drop_table('mind_datasources')
    op.drop_table('datasources')
    op.drop_table('minds')
    
    # Drop extension
    op.execute('DROP EXTENSION IF EXISTS "uuid-ossp"')
