"""add_data_catalog_tables

Revision ID: 005_add_data_catalog_tables
Revises: c617e589a92e
Create Date: 2025-01-27 10:00:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '004_add_data_catalog_tables'
down_revision: str | None = '001_initial_schema_complete'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table('tables',
    sa.Column(
        'id',
        postgresql.UUID(as_uuid=True),
        primary_key=True,
        server_default=sa.text('gen_random_uuid()'),
        nullable=False,
        comment='UUID primary key generated by PostgreSQL'
    ),
    sa.Column(
        'tenant_id',
        sa.String(length=255),
        nullable=False,
        comment='Tenant ID'
    ),
    sa.Column(
        'created_at', 
        sa.DateTime(timezone=True), 
        nullable=True,
        server_default=sa.text('now()'),
        comment='The date and time the record was created'
    ),
    sa.Column(
        'modified_at', 
        sa.DateTime(timezone=True), 
        nullable=True,
        server_default=sa.text('now()'),
        comment='The date and time the record was updated'
    ),
    sa.Column(
        'deleted_at', 
        sa.DateTime(timezone=True), 
        nullable=True,
        comment='The date and time the record was deleted'
    ),
    sa.Column('datasource_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('schema', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['datasource_id'], ['datasources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('columns',
    sa.Column(
        'id',
        postgresql.UUID(as_uuid=True),
        primary_key=True,
        server_default=sa.text('gen_random_uuid()'),
        nullable=False,
        comment='UUID primary key generated by PostgreSQL'
    ),
    sa.Column(
        'tenant_id',
        sa.String(length=255),
        nullable=False,
        comment='Tenant ID'
    ),
    sa.Column(
        'created_at',
        sa.DateTime(timezone=True),
        server_default=sa.func.now(),
        nullable=True,
        comment='The date and time the record was created. Field is optional and not needed when instantiating a new record. It will be automatically set when the record is created in the database.'
    ),
    sa.Column(
        'modified_at',
        sa.DateTime(timezone=True),
        server_default=sa.func.now(),
        nullable=True,
        comment='The date and time the record was updated. Field is optional and not needed when instantiating a new record. It will be automatically set when the record is created in the database.'
    ),
    sa.Column(
        'deleted_at', 
        sa.DateTime(timezone=True), 
        nullable=True,
        comment='The date and time the record was deleted'
    ),
    sa.Column('table_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_value', sa.String(length=500), nullable=True),
    sa.Column('is_nullable', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('column_statistics',
    sa.Column(
        'id',
        postgresql.UUID(as_uuid=True),
        primary_key=True,
        server_default=sa.text('gen_random_uuid()'),
        nullable=False,
        comment='UUID primary key generated by PostgreSQL'
    ),
    sa.Column(
        'tenant_id',
        sa.String(length=255),
        nullable=False,
        comment='Tenant ID'
    ),
    sa.Column(
        'created_at',
        sa.DateTime(timezone=True),
        server_default=sa.func.now(),
        nullable=True,
        comment='The date and time the record was created. Field is optional and not needed when instantiating a new record. It will be automatically set when the record is created in the database.'
    ),
    sa.Column(
        'modified_at',
        sa.DateTime(timezone=True),
        server_default=sa.func.now(),
        nullable=True,
        comment='The date and time the record was updated. Field is optional and not needed when instantiating a new record. It will be automatically set when the record is created in the database.'
    ),
    sa.Column(
        'deleted_at', 
        sa.DateTime(timezone=True), 
        nullable=True,
        comment='The date and time the record was deleted'
    ),
    sa.Column('column_id', sa.UUID(), nullable=False),
    sa.Column('most_common_values', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('most_common_frequencies', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('null_percentage', sa.Float(), nullable=True),
    sa.Column('distinct_values_count', sa.Integer(), nullable=True),
    sa.Column('min_value', sa.String(length=500), nullable=True),
    sa.Column('max_value', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['column_id'], ['columns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('primary_key_constraints',
    sa.Column(
        'id',
        postgresql.UUID(as_uuid=True),
        primary_key=True,
        server_default=sa.text('gen_random_uuid()'),
        nullable=False,
        comment='UUID primary key generated by PostgreSQL'
    ),
    sa.Column(
        'tenant_id',
        sa.String(length=255),
        nullable=False,
        comment='Tenant ID'
    ),
    sa.Column(
        'created_at',
        sa.DateTime(timezone=True),
        server_default=sa.func.now(),
        nullable=True,
        comment='The date and time the record was created. Field is optional and not needed when instantiating a new record. It will be automatically set when the record is created in the database.'
    ),
    sa.Column(
        'modified_at',
        sa.DateTime(timezone=True),
        server_default=sa.func.now(),
        nullable=True,
        comment='The date and time the record was updated. Field is optional and not needed when instantiating a new record. It will be automatically set when the record is created in the database.'
    ),
    sa.Column(
        'deleted_at', 
        sa.DateTime(timezone=True), 
        nullable=True,
        comment='The date and time the record was deleted'
    ),
    sa.Column('table_id', sa.UUID(), nullable=False),
    sa.Column('column_id', sa.UUID(), nullable=False),
    sa.Column('ordinal_position', sa.Integer(), nullable=True),
    sa.Column('constraint_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['column_id'], ['columns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('foreign_key_constraints',
    sa.Column(
        'id',
        postgresql.UUID(as_uuid=True),
        primary_key=True,
        server_default=sa.text('gen_random_uuid()'),
        nullable=False,
        comment='UUID primary key generated by PostgreSQL'
    ),
    sa.Column(
        'tenant_id',
        sa.String(length=255),
        nullable=False,
        comment='Tenant ID'
    ),
    sa.Column(
        'created_at',
        sa.DateTime(timezone=True),
        server_default=sa.func.now(),
        nullable=True,
        comment='The date and time the record was created. Field is optional and not needed when instantiating a new record. It will be automatically set when the record is created in the database.'
    ),
    sa.Column(
        'modified_at',
        sa.DateTime(timezone=True),
        server_default=sa.func.now(),
        nullable=True,
        comment='The date and time the record was updated. Field is optional and not needed when instantiating a new record. It will be automatically set when the record is created in the database.'
    ),
    sa.Column(
        'deleted_at', 
        sa.DateTime(timezone=True), 
        nullable=True,
        comment='The date and time the record was deleted'
    ),
    sa.Column('table_id', sa.UUID(), nullable=False),
    sa.Column('column_id', sa.UUID(), nullable=False),
    sa.Column('referenced_table_id', sa.UUID(), nullable=False),
    sa.Column('referenced_column_id', sa.UUID(), nullable=False),
    sa.Column('constraint_name', sa.String(length=255), nullable=True),
    sa.Column('ordinal_position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['column_id'], ['columns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referenced_column_id'], ['columns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referenced_table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create indexes for better performance
    op.create_index('ix_tables_datasource_id', 'tables', ['datasource_id'])
    op.create_index('ix_tables_name', 'tables', ['name'])
    op.create_index('ix_columns_table_id', 'columns', ['table_id'])
    op.create_index('ix_columns_name', 'columns', ['name'])
    op.create_index('ix_column_statistics_column_id', 'column_statistics', ['column_id'])
    op.create_index('ix_primary_key_constraints_table_id', 'primary_key_constraints', ['table_id'])
    op.create_index('ix_primary_key_constraints_column_id', 'primary_key_constraints', ['column_id'])
    op.create_index('ix_foreign_key_constraints_table_id', 'foreign_key_constraints', ['table_id'])
    op.create_index('ix_foreign_key_constraints_column_id', 'foreign_key_constraints', ['column_id'])
    op.create_index('ix_foreign_key_constraints_referenced_table_id', 'foreign_key_constraints', ['referenced_table_id'])
    op.create_index('ix_foreign_key_constraints_referenced_column_id', 'foreign_key_constraints', ['referenced_column_id'])

    # Add a column to the datasources table to store engine info.
    op.add_column('datasources', sa.Column('engine_info', sa.Text(), nullable=True))


def downgrade() -> None:
    op.drop_index('ix_foreign_key_constraints_referenced_column_id', table_name='foreign_key_constraints')
    op.drop_index('ix_foreign_key_constraints_referenced_table_id', table_name='foreign_key_constraints')
    op.drop_index('ix_foreign_key_constraints_column_id', table_name='foreign_key_constraints')
    op.drop_index('ix_foreign_key_constraints_table_id', table_name='foreign_key_constraints')
    op.drop_index('ix_primary_key_constraints_column_id', table_name='primary_key_constraints')
    op.drop_index('ix_primary_key_constraints_table_id', table_name='primary_key_constraints')
    op.drop_index('ix_column_statistics_column_id', table_name='column_statistics')
    op.drop_index('ix_columns_name', table_name='columns')
    op.drop_index('ix_columns_table_id', table_name='columns')
    op.drop_index('ix_tables_name', table_name='tables')
    op.drop_index('ix_tables_datasource_id', table_name='tables')

    op.drop_table('foreign_key_constraints')
    op.drop_table('primary_key_constraints')
    op.drop_table('column_statistics')
    op.drop_table('columns')
    op.drop_table('tables')

    op.drop_column('datasources', 'engine_info')