"""add_data_catalog_tables

Revision ID: 002_add_data_catalog_tables
Revises: 001_initial_schema_complete
Create Date: 2025-01-27 10:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# DataCatalogStatus enum values (from deleted minds.model.mind_datasource)
DATA_CATALOG_STATUS_VALUES = ["PENDING", "IN_PROGRESS", "COMPLETED", "FAILED"]

# revision identifiers, used by Alembic.
revision: str = "002_add_data_catalog_tables"
down_revision: str | None = "001_initial_schema_complete"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "tables",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="UUID primary key generated by PostgreSQL",
        ),
        sa.Column("tenant_id", sa.String(length=255), nullable=False, comment="Tenant ID"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=True,
            server_default=sa.text("now()"),
            comment="The date and time the record was created",
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(timezone=True),
            nullable=True,
            server_default=sa.text("now()"),
            comment="The date and time the record was updated",
        ),
        sa.Column(
            "deleted_at", sa.DateTime(timezone=True), nullable=True, comment="The date and time the record was deleted"
        ),
        sa.Column("datasource_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("schema", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("type", sa.String(length=50), nullable=True),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["datasource_id"],
            ["datasources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "columns",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="UUID primary key generated by PostgreSQL",
        ),
        sa.Column("tenant_id", sa.String(length=255), nullable=False, comment="Tenant ID"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=True,
            comment="The date and time the record was created. Field is optional and not needed when instantiating a new record. It will be automatically set when the record is created in the database.",
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=True,
            comment="The date and time the record was updated. Field is optional and not needed when instantiating a new record. It will be automatically set when the record is created in the database.",
        ),
        sa.Column(
            "deleted_at", sa.DateTime(timezone=True), nullable=True, comment="The date and time the record was deleted"
        ),
        sa.Column("table_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("data_type", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("default_value", sa.String(length=500), nullable=True),
        sa.Column("is_nullable", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["table_id"], ["tables.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "column_statistics",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="UUID primary key generated by PostgreSQL",
        ),
        sa.Column("tenant_id", sa.String(length=255), nullable=False, comment="Tenant ID"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=True,
            comment="The date and time the record was created. Field is optional and not needed when instantiating a new record. It will be automatically set when the record is created in the database.",
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=True,
            comment="The date and time the record was updated. Field is optional and not needed when instantiating a new record. It will be automatically set when the record is created in the database.",
        ),
        sa.Column(
            "deleted_at", sa.DateTime(timezone=True), nullable=True, comment="The date and time the record was deleted"
        ),
        sa.Column("column_id", sa.UUID(), nullable=False),
        sa.Column("most_common_values", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("most_common_frequencies", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("null_percentage", sa.Float(), nullable=True),
        sa.Column("distinct_values_count", sa.Integer(), nullable=True),
        sa.Column("min_value", sa.String(length=500), nullable=True),
        sa.Column("max_value", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(["column_id"], ["columns.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "primary_key_constraints",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="UUID primary key generated by PostgreSQL",
        ),
        sa.Column("tenant_id", sa.String(length=255), nullable=False, comment="Tenant ID"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=True,
            comment="The date and time the record was created. Field is optional and not needed when instantiating a new record. It will be automatically set when the record is created in the database.",
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=True,
            comment="The date and time the record was updated. Field is optional and not needed when instantiating a new record. It will be automatically set when the record is created in the database.",
        ),
        sa.Column(
            "deleted_at", sa.DateTime(timezone=True), nullable=True, comment="The date and time the record was deleted"
        ),
        sa.Column("table_id", sa.UUID(), nullable=False),
        sa.Column("column_id", sa.UUID(), nullable=False),
        sa.Column("ordinal_position", sa.Integer(), nullable=True),
        sa.Column("constraint_name", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["column_id"], ["columns.id"]),
        sa.ForeignKeyConstraint(["table_id"], ["tables.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "foreign_key_constraints",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="UUID primary key generated by PostgreSQL",
        ),
        sa.Column("tenant_id", sa.String(length=255), nullable=False, comment="Tenant ID"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=True,
            comment="The date and time the record was created. Field is optional and not needed when instantiating a new record. It will be automatically set when the record is created in the database.",
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=True,
            comment="The date and time the record was updated. Field is optional and not needed when instantiating a new record. It will be automatically set when the record is created in the database.",
        ),
        sa.Column(
            "deleted_at", sa.DateTime(timezone=True), nullable=True, comment="The date and time the record was deleted"
        ),
        sa.Column("table_id", sa.UUID(), nullable=False),
        sa.Column("column_id", sa.UUID(), nullable=False),
        sa.Column("referenced_table_id", sa.UUID(), nullable=False),
        sa.Column("referenced_column_id", sa.UUID(), nullable=False),
        sa.Column("constraint_name", sa.String(length=255), nullable=True),
        sa.Column("ordinal_position", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["column_id"], ["columns.id"]),
        sa.ForeignKeyConstraint(["referenced_column_id"], ["columns.id"]),
        sa.ForeignKeyConstraint(["referenced_table_id"], ["tables.id"]),
        sa.ForeignKeyConstraint(["table_id"], ["tables.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "mind_datasource_tables",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="UUID primary key generated by PostgreSQL",
        ),
        sa.Column("tenant_id", sa.String(length=255), nullable=False, comment="Tenant ID"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=True,
            comment="The date and time the record was created. Field is optional and not needed when instantiating a new record. It will be automatically set when the record is created in the database.",
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=True,
            comment="The date and time the record was updated. Field is optional and not needed when instantiating a new record. It will be automatically set when the record is created in the database.",
        ),
        sa.Column(
            "deleted_at", sa.DateTime(timezone=True), nullable=True, comment="The date and time the record was deleted"
        ),
        sa.Column("mind_datasource_id", sa.UUID(), nullable=False),
        sa.Column("table_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["mind_datasource_id"], ["mind_datasources.id"]),
        sa.ForeignKeyConstraint(["table_id"], ["tables.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    # Create indexes for better performance
    op.create_index("ix_tables_datasource_id", "tables", ["datasource_id"])
    op.create_index("ix_tables_name", "tables", ["name"])
    op.create_index("ix_columns_table_id", "columns", ["table_id"])
    op.create_index("ix_columns_name", "columns", ["name"])
    op.create_index("ix_column_statistics_column_id", "column_statistics", ["column_id"])
    op.create_index("ix_primary_key_constraints_table_id", "primary_key_constraints", ["table_id"])
    op.create_index("ix_primary_key_constraints_column_id", "primary_key_constraints", ["column_id"])
    op.create_index("ix_foreign_key_constraints_table_id", "foreign_key_constraints", ["table_id"])
    op.create_index("ix_foreign_key_constraints_column_id", "foreign_key_constraints", ["column_id"])
    op.create_index(
        "ix_foreign_key_constraints_referenced_table_id", "foreign_key_constraints", ["referenced_table_id"]
    )
    op.create_index(
        "ix_foreign_key_constraints_referenced_column_id", "foreign_key_constraints", ["referenced_column_id"]
    )
    op.create_index("ix_mind_datasource_tables_mind_datasource_id", "mind_datasource_tables", ["mind_datasource_id"])
    op.create_index("ix_mind_datasource_tables_table_id", "mind_datasource_tables", ["table_id"])

    # Add a column to the datasources table to store engine info.
    op.add_column("datasources", sa.Column("engine_info", sa.Text(), nullable=True))

    # Add a column to the mind_datasources table to track the status of data catalog loading.
    status_enum = postgresql.ENUM(*DATA_CATALOG_STATUS_VALUES, name="data_catalog_status")
    status_enum.create(op.get_bind())
    op.add_column(
        "mind_datasources",
        sa.Column(
            "status",
            status_enum,
            server_default="PENDING",
            nullable=False,
        ),
    )

    # Create triggers for automatically updating modified_at timestamps
    # Using the function update_modified_at_column from the initial schema
    op.execute("""
        CREATE TRIGGER update_mind_datasource_tables_modified_at
        BEFORE UPDATE ON mind_datasource_tables
        FOR EACH ROW EXECUTE FUNCTION update_modified_at_column();
    """)
    op.execute("""
        CREATE TRIGGER update_tables_modified_at
        BEFORE UPDATE ON tables
        FOR EACH ROW EXECUTE FUNCTION update_modified_at_column();
    """)
    op.execute("""
        CREATE TRIGGER update_columns_modified_at
        BEFORE UPDATE ON columns
        FOR EACH ROW EXECUTE FUNCTION update_modified_at_column();
    """)
    op.execute("""
        CREATE TRIGGER update_column_statistics_modified_at
        BEFORE UPDATE ON column_statistics
        FOR EACH ROW EXECUTE FUNCTION update_modified_at_column();
    """)
    op.execute("""
        CREATE TRIGGER update_primary_key_constraints_modified_at
        BEFORE UPDATE ON primary_key_constraints
        FOR EACH ROW EXECUTE FUNCTION update_modified_at_column();
    """)
    op.execute("""
        CREATE TRIGGER update_foreign_key_constraints_modified_at
        BEFORE UPDATE ON foreign_key_constraints
        FOR EACH ROW EXECUTE FUNCTION update_modified_at_column();
    """)

    # Create function to handle soft deletes for mind_datasource_tables
    op.execute("""
        CREATE OR REPLACE FUNCTION soft_delete_mind_datasource_tables()
        RETURNS TRIGGER AS $$
        BEGIN
            UPDATE mind_datasource_tables
            SET deleted_at = NEW.deleted_at
            WHERE mind_datasource_id = NEW.id
            AND deleted_at IS NULL;
            
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)

    # Create trigger to handle soft deletes for mind_datasource_tables
    op.execute("""
        CREATE TRIGGER trigger_soft_delete_mind_datasource_tables
        AFTER UPDATE OF deleted_at ON mind_datasources
        FOR EACH ROW
        WHEN (NEW.deleted_at IS NOT NULL AND OLD.deleted_at IS NULL)
        EXECUTE FUNCTION soft_delete_mind_datasource_tables();
    """)

    # Create function to handle soft deletes for tables
    op.execute("""
        CREATE OR REPLACE FUNCTION soft_delete_tables()
        RETURNS TRIGGER AS $$
        BEGIN
            UPDATE tables
            SET deleted_at = NEW.deleted_at
            WHERE datasource_id = NEW.id
            AND deleted_at IS NULL;
            
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)

    # Create trigger to handle soft deletes for tables
    op.execute("""
        CREATE TRIGGER trigger_soft_delete_tables
        AFTER UPDATE OF deleted_at ON datasources
        FOR EACH ROW
        WHEN (NEW.deleted_at IS NOT NULL AND OLD.deleted_at IS NULL)
        EXECUTE FUNCTION soft_delete_tables();
    """)

    # Create function to handle soft deletes for columns
    op.execute("""
        CREATE OR REPLACE FUNCTION soft_delete_columns()
        RETURNS TRIGGER AS $$
        BEGIN
            UPDATE columns
            SET deleted_at = NEW.deleted_at
            WHERE table_id = NEW.id
            AND deleted_at IS NULL;
            
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)

    # Create trigger to handle soft deletes for columns
    op.execute("""
        CREATE TRIGGER trigger_soft_delete_columns
        AFTER UPDATE OF deleted_at ON tables
        FOR EACH ROW
        WHEN (NEW.deleted_at IS NOT NULL AND OLD.deleted_at IS NULL)
        EXECUTE FUNCTION soft_delete_columns();
    """)

    # Create function to handle soft deletes for column_statistics
    op.execute("""
        CREATE OR REPLACE FUNCTION soft_delete_column_statistics()
        RETURNS TRIGGER AS $$
        BEGIN
            UPDATE column_statistics
            SET deleted_at = NEW.deleted_at
            WHERE column_id = NEW.id
            AND deleted_at IS NULL;
            
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)

    # Create trigger to handle soft deletes for column_statistics
    op.execute("""
        CREATE TRIGGER trigger_soft_delete_column_statistics
        AFTER UPDATE OF deleted_at ON columns
        FOR EACH ROW
        WHEN (NEW.deleted_at IS NOT NULL AND OLD.deleted_at IS NULL)
        EXECUTE FUNCTION soft_delete_column_statistics();
    """)

    # Create function to handle soft deletes for primary_key_constraints
    op.execute("""
        CREATE OR REPLACE FUNCTION soft_delete_primary_key_constraints()
        RETURNS TRIGGER AS $$
        BEGIN
            -- Case 1: Triggered by tables table
            IF TG_TABLE_NAME = 'tables' THEN
                UPDATE primary_key_constraints
                SET deleted_at = NEW.deleted_at
                WHERE table_id = NEW.id
                AND deleted_at IS NULL;

            -- Case 2: Triggered by columns table
            ELSIF TG_TABLE_NAME = 'columns' THEN
                UPDATE primary_key_constraints
                SET deleted_at = NEW.deleted_at
                WHERE column_id = NEW.id
                AND deleted_at IS NULL;
            END IF;

            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)

    # Create triggers to handle soft deletes for primary_key_constraints
    op.execute("""
        CREATE TRIGGER trigger_soft_delete_primary_key_constraints_from_tables
        AFTER UPDATE OF deleted_at ON tables
        FOR EACH ROW
        WHEN (NEW.deleted_at IS NOT NULL AND OLD.deleted_at IS NULL)
        EXECUTE FUNCTION soft_delete_primary_key_constraints();
    """)
    op.execute("""
        CREATE TRIGGER trigger_soft_delete_primary_key_constraints_from_columns
        AFTER UPDATE OF deleted_at ON columns
        FOR EACH ROW
        WHEN (NEW.deleted_at IS NOT NULL AND OLD.deleted_at IS NULL)
        EXECUTE FUNCTION soft_delete_primary_key_constraints();
    """)

    # Create function to handle soft deletes for foreign_key_constraints
    op.execute("""
        CREATE OR REPLACE FUNCTION soft_delete_foreign_key_constraints()
        RETURNS TRIGGER AS $$
        BEGIN
            -- Case 1: Triggered by tables table (affects both source and referenced tables)
            IF TG_TABLE_NAME = 'tables' THEN
                UPDATE foreign_key_constraints
                SET deleted_at = NEW.deleted_at
                WHERE (table_id = NEW.id OR referenced_table_id = NEW.id)
                AND deleted_at IS NULL;

            -- Case 2: Triggered by columns table (affects both source and referenced columns)
            ELSIF TG_TABLE_NAME = 'columns' THEN
                UPDATE foreign_key_constraints
                SET deleted_at = NEW.deleted_at
                WHERE (column_id = NEW.id OR referenced_column_id = NEW.id)
                AND deleted_at IS NULL;
            END IF;

            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)

    # Create triggers to handle soft deletes for foreign_key_constraints
    op.execute("""
        CREATE TRIGGER trigger_soft_delete_foreign_key_constraints_from_tables
        AFTER UPDATE OF deleted_at ON tables
        FOR EACH ROW
        WHEN (NEW.deleted_at IS NOT NULL AND OLD.deleted_at IS NULL)
        EXECUTE FUNCTION soft_delete_foreign_key_constraints();
    """)
    op.execute("""
        CREATE TRIGGER trigger_soft_delete_foreign_key_constraints_from_columns
        AFTER UPDATE OF deleted_at ON columns
        FOR EACH ROW
        WHEN (NEW.deleted_at IS NOT NULL AND OLD.deleted_at IS NULL)
        EXECUTE FUNCTION soft_delete_foreign_key_constraints();
    """)


def downgrade() -> None:
    # Drop triggers
    op.execute("DROP TRIGGER IF EXISTS trigger_soft_delete_foreign_key_constraints_from_columns ON columns;")
    op.execute("DROP TRIGGER IF EXISTS trigger_soft_delete_foreign_key_constraints_from_tables ON tables;")
    op.execute("DROP TRIGGER IF EXISTS trigger_soft_delete_primary_key_constraints_from_columns ON columns;")
    op.execute("DROP TRIGGER IF EXISTS trigger_soft_delete_primary_key_constraints_from_tables ON tables;")
    op.execute("DROP TRIGGER IF EXISTS trigger_soft_delete_column_statistics ON columns;")
    op.execute("DROP TRIGGER IF EXISTS trigger_soft_delete_columns ON tables;")
    op.execute("DROP TRIGGER IF EXISTS trigger_soft_delete_tables ON datasources;")
    op.execute("DROP TRIGGER IF EXISTS trigger_soft_delete_mind_datasource_tables ON mind_datasources;")
    op.execute("DROP TRIGGER IF EXISTS update_mind_datasource_tables_modified_at ON mind_datasource_tables;")
    op.execute("DROP TRIGGER IF EXISTS update_tables_modified_at ON tables;")
    op.execute("DROP TRIGGER IF EXISTS update_columns_modified_at ON columns;")
    op.execute("DROP TRIGGER IF EXISTS update_column_statistics_modified_at ON column_statistics;")
    op.execute("DROP TRIGGER IF EXISTS update_primary_key_constraints_modified_at ON primary_key_constraints;")
    op.execute("DROP TRIGGER IF EXISTS update_foreign_key_constraints_modified_at ON foreign_key_constraints;")

    # Drop functions
    op.execute("DROP FUNCTION IF EXISTS soft_delete_foreign_key_constraints();")
    op.execute("DROP FUNCTION IF EXISTS soft_delete_primary_key_constraints();")
    op.execute("DROP FUNCTION IF EXISTS soft_delete_column_statistics();")
    op.execute("DROP FUNCTION IF EXISTS soft_delete_columns();")
    op.execute("DROP FUNCTION IF EXISTS soft_delete_tables();")
    op.execute("DROP FUNCTION IF EXISTS soft_delete_mind_datasource_tables();")

    op.drop_index("ix_foreign_key_constraints_referenced_column_id", table_name="foreign_key_constraints")
    op.drop_index("ix_foreign_key_constraints_referenced_table_id", table_name="foreign_key_constraints")
    op.drop_index("ix_foreign_key_constraints_column_id", table_name="foreign_key_constraints")
    op.drop_index("ix_foreign_key_constraints_table_id", table_name="foreign_key_constraints")
    op.drop_index("ix_primary_key_constraints_column_id", table_name="primary_key_constraints")
    op.drop_index("ix_primary_key_constraints_table_id", table_name="primary_key_constraints")
    op.drop_index("ix_column_statistics_column_id", table_name="column_statistics")
    op.drop_index("ix_columns_name", table_name="columns")
    op.drop_index("ix_columns_table_id", table_name="columns")
    op.drop_index("ix_tables_name", table_name="tables")
    op.drop_index("ix_tables_datasource_id", table_name="tables")
    op.drop_index("ix_mind_datasource_tables_table_id", table_name="mind_datasource_tables")
    op.drop_index("ix_mind_datasource_tables_mind_datasource_id", table_name="mind_datasource_tables")
    op.drop_table("foreign_key_constraints")
    op.drop_table("primary_key_constraints")
    op.drop_table("column_statistics")
    op.drop_table("columns")
    op.drop_table("tables")
    op.drop_table("mind_datasource_tables")
    op.drop_column("datasources", "engine_info")
    op.drop_column("mind_datasources", "status")
