"""add_datasource_table

Revision ID: 003_add_datasource_table
Revises: 002_expand_mind_model
Create Date: 2024-01-26 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '003_add_datasource_table'
down_revision: Union[str, None] = '002_expand_mind_model'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('engine', sa.String(length=50), nullable=False),
    sa.Column('connection_data', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'company_id', name='unique_datasource_name_per_company')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datasources')
    # ### end Alembic commands ###
