apiVersion: batch/v1
kind: Job
metadata:
  name: minds-langfuse-benchmarks
  namespace: ${NAMESPACE}
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: minds-langfuse-benchmarks
          image: 168681354662.dkr.ecr.us-east-1.amazonaws.com/minds-langfuse-benchmarks:latest
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args:
            - >
              python scripts/run_dataset_evaluations.py \
                --minds-api-key "$MINDS_API_KEY" \
                --minds-base-url "${MINDS_BASE_URL}" \
                --langfuse-secret-key "$LANGFUSE_SECRET_KEY" \
                --langfuse-public-key "$LANGFUSE_PUBLIC_KEY" \
                --langfuse-host "https://langfuse.dev.mindsdb.com" \
                --filter "postgres"
          env:
            - name: MINDS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mindsdb-secrets
                  key: MINDS_API_KEY
            - name: LANGFUSE_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: mindsdb-secrets
                  key: LANGFUSE_PUBLIC_KEY
            - name: LANGFUSE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: mindsdb-secrets
                  key: LANGFUSE_SECRET_KEY