apiVersion: v1
description: Job Helm Chart, to run a job once during deployment
home: https://github.com/DevOps-Nirvana/Universal-Kubernetes-Helm-Charts
keywords:
- job
- helm
- devops-nirvana
maintainers:
- email: farley@neonsurge.com
  name: Farley Farley
name: job
sources:
- https://devops-nirvana.s3.amazonaws.com/helm-charts/
- https://github.com/DevOps-Nirvana/Universal-Kubernetes-Helm-Charts/charts/job
version: 1.0.0
