deployment:
  serviceAccount:
    enabled: true
    annotations:
      # Gives permission to use the mind-castle kms key
      eks.amazonaws.com/role-arn: arn:aws:iam::065786718370:role/minds-20260204214712848900000002
  

  ingress:
    enabled: true
    name: mindshub-inference
    annotations:
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-origin: "https://console.mindshub.ai, https://mdb.ai, https://hub.mindsdb.com"
      nginx.ingress.kubernetes.io/auth-url: "http://auth.prod.svc.cluster.local:80/v1/authenticate/"
    hosts:
      - host: api.mindshub.ai
        enableMultiPath: true
        paths:
          - path: /v1
            serviceName: mindshub-inference
            servicePort: 80
  
  extraEnvs:

    # ====================================
    # GENERAL SETTINGS
    # ====================================

    - name: ENV
      value: "prod"

    # ====================================
    # LOGGING SETTINGS
    # ====================================

    - name: LOG_LEVEL
      value: "WARNING"

    # ====================================
    # LANGFUSE SETTINGS
    # ====================================

    - name: LANGFUSE_TRACING_ENVIRONMENT
      value: "prod"

    # ====================================
    # MIND CASTLE SETTINGS
    # ====================================

    - name: MIND_CASTLE_AWS_KMS_KEY_ARN
      value: "arn:aws:kms:us-east-1:065786718370:key/1787cc0e-18e5-4c7d-af9f-6f9f01b06f17"
    
    # ====================================
    # STATSIG SETTINGS
    # ====================================

    - name: STATSIG__ENVIRONMENT
      value: "production"
          
