MAX_TOOL_ROUNDS = 25
CONTEXT_PRESSURE_THRESHOLD = 0.7
MAX_CONSECUTIVE_ERRORS = 5
RESILIENCE_NUDGE_AT = 2

NOTABLE_PACKAGES = {
    "numpy",
    "pandas",
    "matplotlib",
    "seaborn",
    "scipy",
    "scikit-learn",
    "requests",
    "httpx",
    "aiohttp",
    "beautifulsoup4",
    "lxml",
    "pillow",
    "sympy",
    "networkx",
    "sqlalchemy",
    "pydantic",
    "rich",
    "tqdm",
    "click",
    "fastapi",
    "flask",
    "django",
    "openai",
    "anthropic",
    "tiktoken",
    "transformers",
    "torch",
    "polars",
    "pyarrow",
    "openpyxl",
    "xlsxwriter",
    "plotly",
    "bokeh",
    "altair",
    "pytest",
    "hypothesis",
    "yaml",
    "pyyaml",
    "toml",
    "tomli",
    "tomllib",
    "jinja2",
    "markdown",
    "pygments",
    "cryptography",
    "paramiko",
    "boto3",
}
