from datetime import datetime
from unittest.mock import Mock
from uuid import UUID

from sqlmodel import Session

from minds.model.base_sql_model import BaseSQLModel


class TestBaseSQLModel:
    """Test cases for BaseSQLModel class."""

    def test_base_sql_model_initialization(self):
        """Test that BaseSQLModel can be instantiated with default values."""
        model = BaseSQLModel()

        assert model.id is None
        assert model.created_on is None
        assert model.modified_on is None

    def test_base_sql_model_with_values(self):
        """Test that BaseSQLModel can be instantiated with provided values."""
        test_id = UUID("12345678-1234-5678-1234-567812345678")
        test_datetime = datetime(2023, 1, 1, 12, 0, 0)

        model = BaseSQLModel(id=test_id, created_on=test_datetime, modified_on=test_datetime)

        assert model.id == test_id
        assert model.created_on == test_datetime
        assert model.modified_on == test_datetime

    def test_model_config_validate_assignment(self):
        """Test that model config has validate_assignment enabled."""
        assert BaseSQLModel.model_config["validate_assignment"] is True

    def test_count_class_method(self):
        """Test the count class method."""

        # Create a concrete subclass for testing since BaseSQLModel is abstract for table operations
        class TestModel(BaseSQLModel, table=True):
            __tablename__ = "test_table"

        # Mock session and query execution
        mock_session = Mock(spec=Session)
        mock_result = Mock()
        mock_result.one.return_value = 5
        mock_session.exec.return_value = mock_result

        # Call the count method
        result = TestModel.count(mock_session)

        # Verify the result
        assert result == 5

        # Verify that exec was called with the correct query
        mock_session.exec.assert_called_once()
        call_args = mock_session.exec.call_args[0][0]

        # Verify it's a select statement with count
        assert hasattr(call_args, "compile")  # It's a SQLAlchemy query

    def test_field_descriptions(self):
        """Test that fields have proper descriptions."""
        fields = BaseSQLModel.model_fields

        assert "UUID primary key generated by PostgreSQL" in fields["id"].description
        assert "The date and time the record was created" in fields["created_on"].description
        assert "The date and time the record was updated" in fields["modified_on"].description

    def test_field_defaults(self):
        """Test that fields have proper default values."""
        fields = BaseSQLModel.model_fields

        assert fields["id"].default is None
        assert fields["created_on"].default is None
        assert fields["modified_on"].default is None

    def test_postgresql_uuid_field_type(self):
        """Test that id field uses PostgreSQL UUID type."""
        # This test verifies the field configuration
        fields = BaseSQLModel.model_fields
        id_field = fields["id"]

        # The field should be configured for PostgreSQL UUID
        assert id_field.annotation == UUID | None

    def test_datetime_fields_timezone_aware(self):
        """Test that datetime fields are configured for timezone awareness."""
        fields = BaseSQLModel.model_fields

        created_on_field = fields["created_on"]
        modified_on_field = fields["modified_on"]

        assert created_on_field.annotation == datetime | None
        assert modified_on_field.annotation == datetime | None
