name: Prod - Build and Deploy on release

on:
  release:
    types: [published]
  workflow_dispatch:

defaults:
  run:
    shell: bash

# Cancel any existing runs of this workflow on the same branch/pr
# We always want to build/deploy/test a new commit over an older one
concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: true

jobs:

  linter:
    # Runs linter
    uses: ./.github/workflows/linter.yml

  tests:
    # Runs tests
    uses: ./.github/workflows/tests.yml

  build:
    runs-on: mdb-dev
    needs: [tests, linter]
    env:
      AWS_REGION: us-east-1
    steps:
      - name: Checkout tag
        uses: actions/checkout@v4
      - name: Pull MindsDB Github Actions
        uses: actions/checkout@v4
        with:
          repository: mindsdb/github-actions
          path: github-actions
      - uses: ./github-actions/setup-env
      - uses: ./github-actions/build-push-ecr
        with:
          module-name: ${{ env.CI_REPOSITORY_SLUG }}
          build-for-environment: production
          image-ref: ${{ env.CI_REF_SLUG }}

  migrate:
    runs-on: mdb-prod
    needs: [ build ]
    strategy:
      fail-fast: false
      matrix:
        environment: [staging, dev, alpha-dev]
    environment:
      name: ${{ matrix.deploy-env }}
      url: ${{ vars.MDB_ENV_URL }}
    # We only want to run one deploy job for an env at a time
    # Don't cancel in progress jobs because it may be for a different PR
    concurrency:
      group: deploy-${{ matrix.deploy-env }}
      cancel-in-progress: false
    env:
      DATABASE_URI: ${{ secrets.MINDS_DB_URI }}
      UV_LINK_MODE: "symlink"
    steps:
      - uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          # Place cache in the tool dir because we mount this in our runnners
          cache-local-path: "/home/runner/_work/_tool/uv-local-cache"
          prune-cache: false
          python-version: ${{ vars.CI_PYTHON_VERSION || '3.10' }}
      - name: Install dependencies
        run: |
          uv pip install --prerelease=allow -r requirements/requirements.txt
      - name: Migrate Database
        run: |
          env PYTHONPATH=../../ alembic upgrade head
  
  deploy:
    runs-on: mdb-prod
    needs: [build]
    environment:
      name: prod
      url: ${{ vars.MDB_ENV_URL }}
    steps:
      - uses: actions/checkout@v4
      - name: Pull MindsDB Github Actions
        uses: actions/checkout@v4
        with:
          repository: mindsdb/github-actions
          path: github-actions
      - uses: ./github-actions/setup-env
      - name: Update IMAGE_TAG in values.yaml
        run: |
          # Install yq if not available
          if ! command -v yq &> /dev/null; then
            sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
            sudo chmod +x /usr/local/bin/yq
          fi
          # Update IMAGE_TAG environment variable value
          yq -i '(.globalEnvsAlias.globalEnvs[] | select(.name == "IMAGE_TAG") | .value) = "development-${{ env.SLUG }}"' deployment/minds-flows/values.yaml
          cat deployment/minds-flows/values.yaml
      - name: Notify of deployment starting
        id: slack
        uses: ./github-actions/slack-deploy-msg
        with:
          channel-id: ${{ secrets.SLACK_DEPLOYMENTS_CHANNEL_ID }}
          status: "started"
          color: "#0099CC"
          env-name: "prod"
          env-url: ${{ vars.MDB_ENV_URL }}
          slack-token: ${{ secrets.GH_ACTIONS_SLACK_BOT_TOKEN }}
      - uses: DevOps-Nirvana/aws-helm-multi-deploy-nodocker@v4
        with:
          environment-slug: prod
          k8s-namespace: prod
          image-tag: production-${{ env.CI_REF_SLUG }}
          timeout: 600s
          wait: "true"  # We need to wait till deployment is finished here, since we're going to test the deployment env
      - name: Notify of deployment finish
        uses: ./github-actions/slack-deploy-msg
        if: always()
        with:
          channel-id: ${{ secrets.SLACK_DEPLOYMENTS_CHANNEL_ID }}
          status: "${{ job.status == 'success' && 'finished' || 'failed' }}"
          color: "${{ job.status == 'success' && '#00C851' || '#FF4444' }}"
          env-name: "prod"
          env-url: ${{ vars.MDB_ENV_URL }}
          slack-token: ${{ secrets.GH_ACTIONS_SLACK_BOT_TOKEN }}
          update-message-id: ${{ steps.slack.outputs.ts }}




