name: Tests

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  unit-tests:
    runs-on: mdb-dev
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.2'
      - name: Run unit tests
        run: make test/unit

  integration-tests:
    runs-on: mdb-dev
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.2'
      - name: Run integration tests
        run: make test/integration
