name: Integration Tests

on:
  workflow_call:
    inputs:
      deploy-env:
        required: true
        type: string
      runs-on:
        required: false
        type: string
        default: mdb-dev

defaults:
  run:
    shell: bash

jobs:
  integration-tests:
    runs-on: ${{ inputs.runs-on }}
    environment:
      name: ${{ inputs.deploy-env }}
      url: ${{ vars.MDB_ENV_URL }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Run integration tests
        run: make test/integration
        env:
          MINDS_API_BASE_URL: ${{ vars.MDB_ENV_URL }}
          GATEWAY_INTERNAL_URL: ${{ vars.GATEWAY_INTERNAL_URL }}
          MINDS_API_KEY: ${{ secrets.MINDS_TEST_USER_API_KEY }}
