job:

  extraEnvs:

    # ====================================
    # GENERAL SETTINGS
    # ====================================

    - name: ENV
      value: "prod"

    # ====================================
    # LANGFUSE SETTINGS
    # ====================================
    
    - name: LANGFUSE_TRACING_ENVIRONMENT
      value: "prod"
    
    # ====================================
    # STATSIG SETTINGS
    # ====================================

    - name: STATSIG__ENVIRONMENT
      value: "production"
          
