job:

  extraEnvs:

    # ====================================
    # GENERAL SETTINGS
    # ====================================

    - name: ENV
      value: "demo"

    # ====================================
    # LANGFUSE SETTINGS
    # ====================================
    
    - name: LANGFUSE_TRACING_ENVIRONMENT
      value: "demo"
    
    # ====================================
    # STATSIG SETTINGS
    # ====================================

    - name: STATSIG__ENVIRONMENT
      value: "development"
          

