job:

  extraEnvs:

    # ====================================
    # GENERAL SETTINGS
    # ====================================

    - name: ENV
      value: "gitlab-dev"

    # ====================================
    # LANGFUSE SETTINGS
    # ====================================
    
    - name: LANGFUSE_TRACING_ENVIRONMENT
      value: "gitlab-dev"
