job:

  extraEnvs:

    # ====================================
    # GENERAL SETTINGS
    # ====================================

    - name: ENV
      value: "terabase-dev"

    # ====================================
    # LANGFUSE SETTINGS
    # ====================================
    
    - name: LANGFUSE_TRACING_ENVIRONMENT
      value: "terabase-dev"

    # ====================================
    # MINDS SETTINGS
    # ====================================

    - name: MINDS__ENABLE_MODEL_SELECTION
      value: "true"
    
    # ====================================
    # STATSIG SETTINGS
    # ====================================

    - name: STATSIG__ENVIRONMENT
      value: "development"
          