from __future__ import annotations

from datetime import datetime
from uuid import UUID

import sqlalchemy as sa
from pydantic import ConfigDict
from sqlalchemy.dialects.postgresql import UUID as PostgreSQLUUID
from sqlmodel import Field, Session, SQLModel, func, select


class BaseSQLModel(SQLModel):
    """Base class for all database models."""

    model_config = ConfigDict(validate_assignment=True)

    id: UUID | None = Field(
        default=None,
        primary_key=True,
        sa_type=PostgreSQLUUID(as_uuid=True),
        sa_column_kwargs={"server_default": sa.text("gen_random_uuid()")},
        description="UUID primary key generated by PostgreSQL",
    )

    created_on: datetime | None = Field(
        default=None,
        sa_type=sa.DateTime(timezone=True),  # type: ignore
        sa_column_kwargs={"server_default": sa.func.now()},
        description=(
            "The date and time the record was created. "
            "Field is optional and not needed when instantiating a new record. "
            "It will be automatically set when the record is created in the database."
        ),
    )

    modified_on: datetime | None = Field(
        default=None,
        sa_type=sa.DateTime(timezone=True),  # type: ignore
        sa_column_kwargs={"onupdate": sa.func.now(), "server_default": sa.func.now()},
        description=(
            "The date and time the record was updated. "
            "Field is optional and not needed when instantiating a new record. "
            "It will be automatically set when the record is created in the database."
        ),
    )

    deleted_at: datetime | None = Field(
        default=None,
        sa_type=sa.DateTime(timezone=True),  # type: ignore
        sa_column_kwargs={"onupdate": sa.func.now(), "server_default": sa.func.now()},
        description=(
            "The date and time the record was deleted. "
            "Field is optional and not needed when instantiating a new record. "
        ),
    )

    @classmethod
    def count(cls, session: Session) -> int:
        return session.exec(select(func.count()).select_from(cls)).one()
