from typing import Any
from uuid import UUID

from mind_castle.sqlalchemy_type import SecretData
from pydantic import BaseModel
from sqlalchemy.dialects.postgresql import JSONB
from sqlmodel import Column, Field

from minds.common.settings.app_settings import get_app_settings
from minds.model.base import BaseSQLModel
from minds.model.message_tracing import MessageTracing
from minds.schemas.chat import Role

settings = get_app_settings()


class SecretDataJSONB(SecretData):
    impl = JSONB


class Message(BaseSQLModel, MessageTracing, table=True):
    __tablename__ = "messages"

    conversation_id: UUID = Field(
        ...,
        foreign_key="conversations.id",
        description="ID of the conversation that this message belongs to",
        index=True,
    )
    role: Role = Field(description="Role of the message")
    content: dict[str, Any] | BaseModel | str | list[Any] = Field(
        default_factory=dict,
        sa_column=Column(SecretDataJSONB(settings.mind_castle.encryption_type)),
        description="Content of the message as JSON",
    )
    sql_query: str | None = Field(
        default=None,
        sa_column=Column(SecretData(settings.mind_castle.encryption_type)),
        description="SQL query generated by the agent to answer the user's question",
    )
